version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:10-jdk

    working_directory: ~/tornimo-spring-cloud-build

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # Buckle up and teeeest!!!
      - run:
          name: Maven Install
          command: mvn install

  deploy:
    docker:
      - image: circleci/openjdk:10-jdk

    working_directory: ~/tornimo-spring-cloud-deploy

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Install AWS Cli
          command: sudo apt-get update && sudo apt-get install -y awscli

      - run:
          name: GPG Prepare Command
          command: eval "$GPG_PREPARE_COMMAND"

      - run:
          name: GPG Download Key
          command: eval "$GPG_DOWNLOAD_COMMAND"

      - run:
          name: GPG Import Command
          command: eval "$GPG_IMPORT_COMMAND"

      - run:
          name: GPG Delete File Command
          command: eval "$GPG_DEL_FILE_COMMAND"

      # Buckle up and deeeeploy!!!
      - run:
          name: Maven Deploy
          command: |
            mvn versions:set -DnewVersion=$CIRCLE_TAG
            mvn --settings .circleci/settings.xml deploy -P central

      - run:
          name: GPG Cleanup Command
          command: eval "$GPG_CLEANUP_COMMAND"

workflows:
  version: 2
  central:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+){2}/
            branches:
              ignore: /.*/